#!/bin/bash
PATTERN="^https?://"
[[ $# -eq 1 && $1 =~ $PATTERN ]] || { echo "Usage: $0 http(s)://real.backend/address"; exit 1; }

python3 << EOF
from http.server import HTTPServer, SimpleHTTPRequestHandler
from socketserver import ThreadingMixIn

import urllib.request
import urllib.error

BACKEND = "$1"
API_PREFIX = "/api"  # какой префикс проксировать

class Handler(SimpleHTTPRequestHandler):
    def do_OPTIONS(self): self._proxy()
    def do_GET(self):
        if self.path.startswith(API_PREFIX): self._proxy()
        else: super().do_GET()
    def do_POST(self):
        if self.path.startswith(API_PREFIX): self._proxy()
        else: super().do_POST()

    def _proxy(self):
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length) if length else None

        req = urllib.request.Request(
            BACKEND + self.path,
            data=body,
            method=self.command
        )
        # for k, v in self.headers.items():
        #     if k.lower() not in ("host", "content-length"):
        #         req.add_header(k, v)
        # req.add_header("Host", BACKEND.replace("https://", ""))
        # передаём только нужные заголовки
        if self.headers.get("Content-Type"):
            req.add_header("Content-Type", self.headers["Content-Type"])
        if self.headers.get("Authorization"):
            req.add_header("Authorization", self.headers["Authorization"])
        if self.headers.get("Cookie"):
            req.add_header("Cookie", self.headers["Cookie"])

        try:
            resp = urllib.request.urlopen(req)
        except urllib.error.HTTPError as e:
            resp = e
        except Exception as e:
            print("PROXY ERROR:", e)
            self.send_response(502)
            self.end_headers()

        self.send_response(resp.status)
        for k, v in resp.headers.items():
            if k.lower() not in ("transfer-encoding",):
                self.send_header(k, v)
        self.end_headers()
        self.wfile.write(resp.read())

# HTTPServer(("localhost", 4000), Handler).serve_forever()
class ThreadingHTTPServer(ThreadingMixIn, HTTPServer):
    daemon_threads = True

ThreadingHTTPServer(("localhost", 4000), Handler).serve_forever()
EOF